// Barrel exports para dashboard
export { default as AdminTabNavigation } from './AdminTabNavigation'
export { default as ContactRequestsTab } from './ContactRequestsTab'
export { default as OverviewTab } from './OverviewTab'
export { default as SettingsTab } from './SettingsTab'
export { default as UsersTab } from './UsersTab'
export { default as QuickMetrics } from './QuickMetrics'
export { default as SystemAlerts } from './SystemAlerts'
export { default as QuickActions } from './QuickActions'
export { default as ContactRequestsHeader } from './ContactRequestsHeader'
export { default as ContactRequestsStats } from './ContactRequestsStats'
export { default as ContactRequestItem } from './ContactRequestItem'
export { default as ContactModal } from './ContactModal'
export { default as ContractDetailsModal } from './ContractDetailsModal'