// Barrel exports para componentes admin principales
export { default as AdminDashboard } from './AdminDashboard'
export { default as AdminDashboardSimple } from './AdminDashboardSimple'
export { default as AffiliateManagement } from './AffiliateManagement'
export { default as AmbulanceManagement } from './AmbulanceManagement'
export { default as AssignmentMap } from './AssignmentMap'
export { default as CorporateContractManagement } from './CorporateContractManagement'
export { default as EmergencyTracking } from './EmergencyTracking'
export { default as ExternalEntityManagement } from './ExternalEntityManagement'
export { default as ExternalUsersManagement } from './ExternalUsersManagement'
export { default as NotificationSystem } from './NotificationSystem'
export { default as PlanConfiguration } from './PlanConfiguration'
export { default as RegistrationManagement } from './RegistrationManagement'
export { default as ReportsAnalytics } from './ReportsAnalytics'
export { default as RevenueManagement } from './RevenueManagement'
export { default as SurveyManagement } from './SurveyManagement'
export { default as UserManagement } from './UserManagement'

// Re-export sub-modules
export * from './dashboard'
export * from './affiliates'
export * from './ambulance'
export * from './corporate'
export * from './emergency'
export * from './external'
export * from './externalUsers'
export * from './map'
export * from './notifications'
export * from './planconfig'
export * from './registration'
export * from './reports'
export * from './revenue'
export * from './shared'
export * from './survey'
export * from './user'
export * from './users'